"""added users

Revision ID: dd44e7d7a596
Revises: 44691eb3c46c
Create Date: 2025-09-19 15:12:44.033638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd44e7d7a596'
down_revision: Union[str, Sequence[str], None] = '44691eb3c46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_phone_number_key'), 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_unique_constraint('uq_contact_email_user', 'contacts', ['email', 'user_id'])
    op.create_unique_constraint('uq_contact_phone_user', 'contacts', ['phone_number', 'user_id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_constraint('uq_contact_phone_user', 'contacts', type_='unique')
    op.drop_constraint('uq_contact_email_user', 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_unique_constraint(op.f('contacts_phone_number_key'), 'contacts', ['phone_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
