"""Initial migration11

Revision ID: dde02110b4a7
Revises: 6ac34efbb643
Create Date: 2025-09-11 13:57:20.420368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde02110b4a7'
down_revision: Union[str, Sequence[str], None] = '6ac34efbb643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Contacts_last_name'), 'Contacts', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Contacts_last_name'), table_name='Contacts')
    # ### end Alembic commands ###
